//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Faturalar
    {
        public int FaturaID { get; set; }
        public int MusteriID { get; set; }
        public int KamyonID { get; set; }
        public int SoforID { get; set; }
        public System.DateTime Tarih { get; set; }
        public int Miktar { get; set; }
        public string FaturaSeriNo { get; set; }
        public int DurumID { get; set; }
    
        public virtual OdenmeDurumlari OdenmeDurumlari { get; set; }
        public virtual tbl_Kamyonlar tbl_Kamyonlar { get; set; }
        public virtual tbl_Musteri tbl_Musteri { get; set; }
        public virtual tbl_Soforler tbl_Soforler { get; set; }
    }
}
